Document: fonts-averia
Title: Debian fonts-averia Manual
Author: <insert document author here>
Abstract: This manual describes what fonts-averia is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fonts-averia/fonts-averia.sgml.gz

Format: postscript
Files: /usr/share/doc/fonts-averia/fonts-averia.ps.gz

Format: text
Files: /usr/share/doc/fonts-averia/fonts-averia.text.gz

Format: HTML
Index: /usr/share/doc/fonts-averia/html/index.html
Files: /usr/share/doc/fonts-averia/html/*.html
